# on: push
# name: deploy
# jobs:
#   web-deploy:
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: Get latest code
#       uses: actions/checkout@v3
    
#     - name: Sync files
#       uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#       with:
#         server: 144.217.70.157
#         username: towb.esko3x
#         password: ${{ secrets.FTP_PASSWORD }}
#         exclude: |
#                 **/.git*
#                 **/.git*/**
                
